name: tabnews
description: Tabnews dart api.
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  # HTTP requests:
  http: ^1.2.1

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
